//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class WpfApp1Entities : DbContext
    {
        private static WpfApp1Entities _context;

        public static WpfApp1Entities GetContext()
        {
            if (_context == null)
                _context = new WpfApp1Entities();

            return _context;
        }

        public WpfApp1Entities()
            : base("name=WpfApp1Entities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        // Таблица User
        public virtual DbSet<User> User { get; set; }
    }
}
